# Generated by Django 5.0.6 on 2024-06-01 14:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('TaskId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('TaskTitle', models.CharField(max_length=100)),
                ('TaskDescription', models.CharField(max_length=300)),
                ('TaskCreationTime', models.DateTimeField(default=datetime.datetime.now)),
                ('TaskStatus', models.CharField(default='Pending', max_length=15)),
                ('TaskOfUserId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='todoApp.users')),
            ],
        ),
    ]
