# Generated by Django 5.0.6 on 2024-06-01 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='TaskOfUserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoApp.users'),
        ),
    ]
