# Generated by Django 5.0.6 on 2024-06-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0003_alter_task_taskofuserid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='TaskStatus',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'In Progress'), ('3', 'Completed')], default='1', max_length=15),
        ),
    ]
