# Generated by Django 5.0.6 on 2024-06-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0004_alter_task_taskstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='TaskCompletedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='TaskUpdatedAt',
            field=models.DateTimeField(null=True),
        ),
    ]
